server:
  port: 5000

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    locations: classpath:db/migration
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}

jwt:
  issuer: jwt_token_security
  expiration: 3600
  secret: ${SECRET}